name: prod CD
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Authenticate on GCS
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: 'roti-281008'
        service_account_key: ${{ secrets.GCP_KEY }}

    - name: npm setup
      run: |
        npm i
        npm run build
    - name: deploy
      run: gcloud app deploy --quiet

    - name: The job has succeeded Notify
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: tech-all
        SLACK_ICON: 'https://66.media.tumblr.com/82bc0000f3e388904e8c6c7ad9aceecd/tumblr_p56p7bBYBH1x0h5yoo9_250.jpg'
        SLACK_MESSAGE: 'でぷろいしたらぁよ でぷろいしたらぁよ!!'
        SLACK_TITLE: デプロイ成功
        SLACK_USERNAME: ポプ子
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
    - name: The job has failed Notify
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: tech-all
        SLACK_ICON: 'https://66.media.tumblr.com/35f0532c12e1cfaaf24f25d38136d2ed/tumblr_p3ldqqFbcG1slg4jbo1_250.png'
        SLACK_MESSAGE: 'でぷろいさしたれや!!'
        SLACK_TITLE: デプロイ失敗
        SLACK_USERNAME: ピピ美
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
